from __future__ import annotations

import argparse
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from pprint import pformat

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "accessible_mail" / "i18n_fr.py"
GUIDE_OUTPUT_PATH = PROJECT_ROOT / "accessible_mail" / "guide_fr.py"
INSTALLER_INFO_SOURCE = PROJECT_ROOT / "installer_info_en.txt"
INSTALLER_INFO_OUTPUT = PROJECT_ROOT / "installer_info_fr.txt"
INSTALLER_README_SOURCE = PROJECT_ROOT / "installer_readme_en.txt"
INSTALLER_README_OUTPUT = PROJECT_ROOT / "installer_readme_fr.txt"
PLACEHOLDER_PATTERN = re.compile(r"\{\d+\}|\t")

sys.path.insert(0, str(PROJECT_ROOT))

from accessible_mail.config import APP_VERSION
from accessible_mail.i18n import ENGLISH_TRANSLATIONS, _DYNAMIC_ENGLISH
from accessible_mail.translation import translate_text_with_google

MANUAL_TRANSLATIONS = {
    "Arabic": "Arabe",
    "English": "Anglais",
    "French": "Français",
    "Settings": "Paramètres",
    "Application language": "Langue de l'application",
    "Application language:": "Langue de l'application :",
    "Application commands": "Commandes de l'application",
    "Application notifications": "Notifications de l'application",
    "Application guide text": "Texte du guide de l'application",
    "Inbox": "Boîte de réception",
    "Spam": "Courrier indésirable",
    "Sent": "Messages envoyés",
    "All Mail": "Tous les messages",
    "Trash": "Corbeille",
    "Item actions": "Actions de l'élément",
    "Opens commands for the selected attachment, image, or link directly.": "Ouvre directement les commandes de la pièce jointe de l'image ou du lien sélectionné.",
    "Item viewer": "Visionneuse des éléments",
    "Item viewer:": "Visionneuse des éléments :",
    "Check for updates": "Rechercher des mises à jour",
    "Power Accessible Mail Guide": "Guide de Power Accessible Mail",
    "Trash scan completed": "Analyse de la corbeille achevée",
    "Added attachments:": "Pièces jointes ajoutées :",
    "Added attachments list": "Liste des pièces jointes ajoutées",
    "Add attachment": "Ajouter une pièce jointe",
    "Add an attachment to the message": "Ajouter une pièce jointe au message",
    "Choose message attachments": "Choisir les pièces jointes du message",
    "Remove selected attachment": "Retirer la pièce jointe sélectionnée",
    "Open selected attachment": "Ouvrir la pièce jointe sélectionnée",
    "Save selected attachment": "Enregistrer la pièce jointe sélectionnée",
    "Save all attachments at once": "Enregistrer toutes les pièces jointes en une fois",
    "Open selected link": "Ouvrir le lien sélectionné",
    "Copy selected link": "Copier le lien sélectionné",
    "Link copied to the clipboard.": "Lien copié dans le presse-papiers.",
    "Unable to open the clipboard to copy the link.": "Impossible d'ouvrir le presse-papiers pour copier le lien.",
}


def translate_template(text: str) -> str:
    translated = MANUAL_TRANSLATIONS.get(text)
    if translated is not None:
        return translated

    tokens: dict[str, str] = {}

    def protect(match: re.Match[str]) -> str:
        token = f"__PAM_TOKEN_{len(tokens)}__"
        tokens[token] = match.group(0)
        return token

    protected = PLACEHOLDER_PATTERN.sub(protect, text)
    translated = translate_text_with_google(protected, target_language="fr")
    for token, original in tokens.items():
        translated = translated.replace(token, original)
    return translated


def translate_catalog(values: list[str]) -> dict[str, str]:
    unique_values = list(dict.fromkeys(values))
    translations: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=6) as executor:
        pending = {
            executor.submit(translate_template, value): value
            for value in unique_values
        }
        for index, future in enumerate(as_completed(pending), start=1):
            source = pending[future]
            translations[source] = future.result()
            print(f"Translated {index}/{len(unique_values)}")
    return translations


def generate_catalog() -> None:
    exact_values = list(ENGLISH_TRANSLATIONS.values())
    dynamic_values = [replacement for _pattern, replacement in _DYNAMIC_ENGLISH]
    translated = translate_catalog(exact_values + dynamic_values)

    exact_catalog = {
        source: translated[english]
        for source, english in ENGLISH_TRANSLATIONS.items()
    }
    dynamic_catalog = tuple(translated[english] for english in dynamic_values)
    output = (
        "from __future__ import annotations\n\n"
        "# Generated by scripts/generate_i18n_fr.py and reviewed in source control.\n"
        f"FRENCH_TRANSLATIONS: dict[str, str] = {pformat(exact_catalog, width=120, sort_dicts=False)}\n\n"
        f"FRENCH_DYNAMIC_TEMPLATES: tuple[str, ...] = {pformat(dynamic_catalog, width=120)}\n"
    )
    OUTPUT_PATH.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH}")


def generate_guide(french_readme: str) -> None:
    guide_output = (
        "from __future__ import annotations\n\n"
        "# Generated by scripts/generate_i18n_fr.py and reviewed in source control.\n"
        f"_SOURCE_VERSION = {APP_VERSION!r}\n"
        f"_FRENCH_PROGRAM_GUIDE = {french_readme!r}\n\n"
        "def french_program_guide(version: str) -> str:\n"
        "    return _FRENCH_PROGRAM_GUIDE.replace(_SOURCE_VERSION, version, 1)\n"
    )
    GUIDE_OUTPUT_PATH.write_text(guide_output, encoding="utf-8", newline="\n")
    print(f"Wrote {GUIDE_OUTPUT_PATH}")


def generate_documents() -> None:
    french_info = translate_template(
        INSTALLER_INFO_SOURCE.read_text(encoding="utf-8-sig")
    )
    french_readme = translate_template(
        INSTALLER_README_SOURCE.read_text(encoding="utf-8-sig")
    )
    INSTALLER_INFO_OUTPUT.write_text(
        french_info + "\n",
        encoding="utf-8-sig",
        newline="\n",
    )
    INSTALLER_README_OUTPUT.write_text(
        french_readme + "\n",
        encoding="utf-8-sig",
        newline="\n",
    )
    print(f"Wrote {INSTALLER_INFO_OUTPUT}")
    print(f"Wrote {INSTALLER_README_OUTPUT}")
    generate_guide(french_readme)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--documents-only",
        action="store_true",
        help="Regenerate only the French installer documents and application guide.",
    )
    parser.add_argument(
        "--guide-from-existing-readme",
        action="store_true",
        help="Regenerate the application guide without contacting the translation service.",
    )
    arguments = parser.parse_args()
    if arguments.guide_from_existing_readme:
        generate_guide(INSTALLER_README_OUTPUT.read_text(encoding="utf-8-sig").strip())
        return
    if not arguments.documents_only:
        generate_catalog()
    generate_documents()


if __name__ == "__main__":
    main()
